# Generated by Django 4.2.7 on 2023-11-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_name_review_book_name_alter_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book_name',
            new_name='book',
        ),
    ]
