# Generated by Django 4.2.7 on 2023-11-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rename_book_name_review_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='name',
        ),
    ]
