# Generated by Django 4.2.7 on 2023-11-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_review_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='book',
        ),
    ]
